### ISSUE TITLE
Uncovered properties in mutation testing?

### ISSUE THREAD

**Issue by sinnbeck** [pestphp/pest#1249] opened 2024-09-13 09:09 UTC
I am making sure a job has the expected delay

```php
it('is delayed', function () {
    $job = app(ProcessWebhookJob::class);

    expect($job->delay)->toBe(5);

});
```
But it claims that it can change the value, and still work as expected
![image](https://github.com/user-attachments/assets/40b6488b-648e-49dd-9cfa-d0595088df34)

**Comment by henzeb** [comment] 2024-09-13 11:03
have the same issue. when changing manually, the test fails.

**Comment by gehrisandro** [comment] 2024-09-13 13:56
duplicate of https://github.com/pestphp/pest/issues/1231

**Closed as completed** 2024-09-13 14:31 UTC
