### ISSUE TITLE
[2.x] Performance issue with `with`.

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#639] opened 2023-01-10 17:38 UTC
@freekmurze reported that the following test takes seconds to run:

```
it('tests')->with(range(1,500));
```

**Comment by alexmanase** [comment] 2023-02-02 11:44
Is this still an issue? I ran the following test in `Playground.php`, and it was really fast.

```php
it('has good range performance', function ($item) {
    expect($item)->toEqual($item);
})->with(range(1, 500));
```

It took 0.2s to run.

Repo: https://github.com/alexmanase/pest/tree/fix/performance-issue-with-with

**Comment by freekmurze** [comment] 2023-02-02 12:44
I tried it again, and it seems to be performing well now. Probably the problem was caused by something between the computer and my chair 🙂 

Let's close this issue.

**Closed as completed** 2023-02-02 12:47 UTC
