### ISSUE TITLE
Not seeing exception when running in PhpStorm

### ISSUE THREAD

**Issue by moshe-autoleadstar** [pestphp/pest#800] opened 2023-05-04 11:06 UTC
I have a test:

```
<?php

it('works', function () {
    //expect(true)->toBeTrue();
    throw new \Exception('watup');
});
```

When I run this in PhpStorm, I see the following output:
```
[docker-compose://[/Users/.../docker-compose.yml]:web/]:php /var/www/html/vendor/pestphp/pest/bin/pest --teamcity /var/www/html/tests/Feature/ExampleTest.php

This test did not perform any assertions

  Tests:    1 failed (0 assertions)
  Duration: 0.47s


Process finished with exit code 2
```

When I do an assertion (uncomment the line: `expect(true)->toBeTrue();`), then I do see the exception.

**Comment by olivernybroe** [comment] 2023-05-04 16:40
@moshe-autoleadstar what PhpStorm and pest plugin version?

**Comment by moshe-autoleadstar** [comment] 2023-05-04 19:45
> @moshe-autoleadstar what PhpStorm and pest plugin version?

PhpStorm 2022.3.1
Build #PS-223.8214.64

Pest Plugin 1.9.2

**Comment by moshe-autoleadstar** [comment] 2023-05-04 19:54
Also in PhpStorm 2023.1.1 (Build #PS-231.8770.68)

**Comment by HakwonChile** [comment] 2023-05-06 06:10
the same problem
This test did not perform any assertions

**Comment by olivernybroe** [comment] 2023-05-10 07:19
@fabio-ivona I am gonna unassign myself as I don't have time at the moment to work on this. Hopefully someone in here does :)

**Comment by nunomaduro** [comment] 2023-05-10 08:17
The issue comes from this file: https://github.com/pestphp/pest/blob/2.x/src/Logging/TeamCity/TeamCityLogger.php.

**Comment by dejagersh** [comment] 2023-05-10 11:12
This issue occurs in my project where I use pestphp 2.6.0, but does not happen in my "old" projects where pestphp 1.16 is used.

**Comment by gehrisandro** [comment] 2023-05-10 20:25
I digged deeper into this issue and it seems to be a tricky one. My findings so far:

The problem is definitively related to a change in PHPUnit in the latest version (10.1.2). Before this change a test throwing an exception only triggered a `PHPUnit\Event\Test\Errored` event. But now it also triggers a `PHPUnit\Event\Test\ConsideredRisky` event in case if the test did not any assertions before the exception was thrown.

This is also visible in the default output of PHPUnit:
**Test**
```php
    public function test_error_behaviour(): void
    {
        throw new Exception('test error');
        $this->assertTrue(true);
    }
```

**Output PHPUnit 10.1.1**
```bash
PHPUnit 10.1.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.14
Configuration: /Users/sandro/Code/phpunit-test/phpunit.xml

E                                                                   1 / 1 (100%)

Time: 00:00.011, Memory: 8.00 MB

There was 1 error:

1) Tests\Unit\ExampleTest::test_error_behaviour
Exception: test error

/Users/sandro/Code/phpunit-test/tests/Unit/ExampleTest.php:15

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

```

**Output PHPUnit 10.1.2**
```bash
PHPUnit 10.1.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.14
Configuration: /Users/sandro/Code/phpunit-test/phpunit.xml

E                                                                   1 / 1 (100%)

Time: 00:00.009, Memory: 8.00 MB

There was 1 error:

1) Tests\Unit\ExampleTest::test_error_behaviour
Exception: test error

/Users/sandro/Code/phpunit-test/tests/Unit/ExampleTest.php:15

--

There was 1 risky test:

1) Tests\Unit\ExampleTest::test_error_behaviour
This test did not perform any assertions

/Users/sandro/Code/phpunit-test/tests/Unit/ExampleTest.php:13

ERRORS!
Tests: 1, Assertions: 0, Errors: 1, Risky: 1.
```

Having this extra `ConsideredRisky` event we have two issues in the Teamcity output:

1) The count of **passed** tests is too low, because the same tests is subtracted twice:
```php
        $numberOfPassedTests = $result->numberOfTestsRun()
            - $result->numberOfTestErroredEvents() // <-- here
            - $result->numberOfTestFailedEvents()
            - $result->numberOfTestSkippedEvents()
            - $result->numberOfTestsWithTestConsideredRiskyEvents() // <-- AND here
            - $result->numberOfTestMarkedIncompleteEvents();
```
https://github.com/pestphp/pest/blob/2.x/src/Logging/TeamCity/Converter.php#L191

2) The exception is not shown by PHPStorm because there are two entries for the same test (name="error") in the TeamCity output and only the second one is shown:
```
...
##teamcity[testFailed name='error' message='Exception: test error' details='at tests/Unit/ExampleTest.php:5|nat vendor/pestphp/pest/src/Factories/TestCaseMethodFactory.php:100|nat vendor/pestphp/pest/src/Concerns/Testable.php:302|nat vendor/pestphp/pest/src/Support/ExceptionTrace.php:28|nat vendor/pestphp/pest/src/Concerns/Testable.php:302|nat vendor/pestphp/pest/src/Concerns/Testable.php:221|nat vendor/pestphp/pest/src/Kernel.php:86' flowId='78739']
##teamcity[testIgnored name='error' message='This test did not perform any assertions' details='' flowId='78739']
...
```

----

To be honest I am not sure how to proceed here. My thoughts so far:

Maybe triggering the two events for the same test is not intended in PHPUnit and it is a bug on their end, but I don't think so.

If we want to fix this on the Pest side we have to calculate the number of successful tests differently by checking every event if there is another event for the same test. This seems doable to me.

For the second problem we would have to store all the events instead of writing them to the output directly and then filter them to only pass the most important event to the output. But this looks like a massive change compared to the current behaviour and I would like to hear your thought before continuing.

Last but not least it would also be possible that the second problem is on PHPStorm side and they should show two or more messages for the same test. I am not familiar with the TeamCity specifications.

@nunomaduro @olivernybroe

**Comment by nunomaduro** [comment] 2023-05-10 22:19
@gehrisandro Thank you so much for looking into this complicated issue. Can you check if we are addressing already issue in our Collision printer? https://github.com/nunomaduro/collision/blob/v7.x/src/Adapters/Phpunit/Printers/DefaultPrinter.php. If yes, maybe the solution can be found on Collision itself already.

**Comment by olivernybroe** [comment] 2023-05-11 04:46
@nunomaduro collision has a state class it uses for calculating tests etc.

@gehrisandro interesting findings, have you checked how phpunit gets around this themselves in their teamcity printer? 👀

**Comment by gehrisandro** [comment] 2023-05-11 04:52
@olivernybroe Currently checking PHPUnits Teamcity logger. As far as I saw, they do log "risky" tests with a `testFailed` message and then PHPStorm does show both messages correctly.

This seems an easy change to our Teamcity Logger but I have to check what the side effects will be first.

**Comment by olivernybroe** [comment] 2023-05-11 04:57
@gehrisandro side effect I can see is tests with no assertions will be shown as failed instead of skipped going forward 🤔 
I don't think that would be a big problem 👀

**Comment by gehrisandro** [comment] 2023-05-11 05:30
@olivernybroe 

Yes this exactly what will happen. "risky" tests are marked as failed.

But that's actually what Teamcity with PHPUnit is doing:

**PHPUnit**
![Screenshot 2023-05-11 at 07 20 28](https://github.com/pestphp/pest/assets/25097194/dfb618c0-c5cc-4113-9731-c7bdec7b548b)

**Pest (not modified)**
![Screenshot 2023-05-11 at 07 21 43](https://github.com/pestphp/pest/assets/25097194/89a756ad-d30f-48aa-9a17-d5b707eaee92)

My question here is, if it is intended that Pest behaves differently than PHPUnit or not?

---

Regarding the test counts I looked into collision and the state class you mentioned. This works seems to work properly with the latest PHPUnit version but I am not sure if the Teamcity logger can make use of it easily because the state is used in a different way.
But I can give it a try later today.

**Comment by olivernybroe** [comment] 2023-05-11 05:51
@gehrisandro what does the pest test summary say? I would say it has to be as close it can to that 👀 

E.g. if summary says risky for them, we should do the same. 


A simple solution is add a new property which will store the last printed test name. Then check if the current test name is the same as the last printed, if that is true, then don't print it again 👀 very little memory overhead from that. 

For the test count, we could just add a simple increment in all the event methods and for it to not count twice, we reuse the check that I proposed earlier 🤔


In regards to the State class, I think I choose to not use it because there was a lot of overhead with it and a few things I couldn't control with it, but might remember wrongly.

**Comment by gehrisandro** [comment] 2023-05-11 20:43
@olivernybroe Thank you for your valuable hints.

I think I found a way to fix the issues and reflect this within the tests.

cc @nunomaduro

**Closed as completed** 2023-05-13 21:15 UTC
