### ISSUE TITLE
[Bug]: Configured test; Absence of "get" naming convention causes an error

### ISSUE THREAD

**Issue by samihsoylu** [pestphp/pest#927] opened 2023-08-22 18:13 UTC
### What Happened

```
➜  vendor/bin/pest

   FAIL  Tests\Integration\ExampleTest
  ✓ example                                                                                                   0.01s
  ⨯ example

   PASS  Tests\Unit\ExampleTest
  ✓ example
  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   FAILED  Tests\Integration\ExampleTest > example                                                 ShouldNotHappen
  This should not happen - please create an new issue here: https://github.com/pestphp/pest.

  Issue: Method testKit not found.
  PHP version: 8.2.3
  Operating system: Darwin
  str_replace(): Argument #3 ($subject) must be of type array|string, null given

  at vendor/filp/whoops/src/Whoops/Exception/FrameCollection.php:43
     39▕      * @return FrameCollection
     40▕      */
     41▕     public function filter($callable)
     42▕     {
  ➜  43▕         $this->frames = array_values(array_filter($this->frames, $callable));
     44▕         return $this;
     45▕     }
     46▕
     47▕     /**
```

### How to Reproduce

Pest
```php
uses(IntegrationTestCaseTrait::class)
    ->group('Integration')
    ->in('Integration');

uses()
    ->group('Unit')
    ->in('Unit');
```

Trait
```php
trait IntegrationTestCaseTrait
{
    public function testKit(): TestKit
    {
        return new TestKit(getContainer());
    }
}
```

Actual test:
```php
test('example', function () {
    expect($this->testKit())->toBeInstanceOf(TestKit::class);
});
```

### Pest Version

2.16

### PHP Version

8.2.3

### Operation System

macOS

### Notes

The issue goes away if I name the method to `getTestKit()` which is very strange.

**Comment by devajmeireles** [comment] 2023-08-22 18:24
Hey, @samihsoylu ! Thanks for your report.

I was able to reproduce the bug. The Pest team will be notified about that. Feel to free to open a PR providing the fix.

**Comment by devajmeireles** [comment] 2023-08-23 19:30
@samihsoylu ! Thanks for your report.

After a few tests and contacting the Pest team, I was able to understand that the error happens because the method name starts with `tests` prefix, so the PHPUnit thinks that's a test. If you rename it to the `abcKit` the test will work successfully.

According to our organization, I'll close this issue. Feel free to open a new issue whenever necessary.

**Closed as completed by devajmeireles** 2023-08-23 19:30 UTC
Labels: bug
