### ISSUE TITLE
Datasets not working if use a real data from databases.

### ISSUE THREAD

**Issue by developerabdan** [pestphp/pest#938] opened 2023-08-25 17:56 UTC
I have a scenarios using a real data, that checking if the employee can access the page. Actually there's a lot of logic in the test, but i decided to not put in this example below.

To Reproduce:
```
<?php
function createDataSet(): array{
    $employee = \App\Models\Employee::get();
    $map = $employee->mapWithKeys(function($item){
        return [$item->name => $item];
    });
    return $map->toArray();
}
it('employee can access the page', function ($employee) {
    $response = $this->get('/');
    $response->assertStatus(200);
})->with(fn()=> createDataSet());
```

when trying to run the test, the output:

` No tests found.`

**Comment by devajmeireles** [comment] 2023-08-25 20:34
Hey, @developerabdan ! Thanks for your report.

I was not able to reproduce the same issue. Your test case sounds a bit wrong to me. Please, review the docs: https://pestphp.com/docs/datasets

According to our organization, I'll close this issue. Feel free to open a new issue whenever necessary.

**Closed as completed by devajmeireles** 2023-08-25 20:34 UTC
Labels: unreproducible
