### ISSUE TITLE
[Bug]: Pest is running tests inside groups that are excluded in phpunit.xml

### ISSUE THREAD

**Issue by edgrosvenor** [pestphp/pest#916] opened 2023-08-17 20:49 UTC
### What Happened

After upgrading to pest 2.15.0 (previously using 2.10.1), pest no longer appears to honor the following portion of my phpunit.xml file:

```
<groups>
        <exclude>
            <group>integration</group>
        </exclude>
    </groups>
```

So my external service integration tests, tagged with that group using a docblock `@group integration` are being run by default.

### How to Reproduce

Attempt to exclude a group from the default test run in phpunit.xml and run pest

### Pest Version

2.15.0

### PHP Version

8.2.6

### Operation System

macOS

**Comment by devajmeireles** [comment] 2023-08-17 21:56
Hey, @edgrosvenor ! Thanks for your report.

First of all, I'll try to reproduce that. Soon as possible I update here.

**Comment by devajmeireles** [comment] 2023-08-18 19:47
Hey, @edgrosvenor .

I was not able to reproduce this:

1. `phpunit.xml`:
 
![CleanShot 2023-08-18 at 4 45 07](https://github.com/pestphp/pest/assets/60591772/6176c9ff-cfad-42cf-8f38-72df897f94c4)

2. Test:

![CleanShot 2023-08-18 at 4 46 16](https://github.com/pestphp/pest/assets/60591772/f2a66d09-5bdd-46f2-9241-b0dedf128f19)

According to that, I presume it might be some problem in your environment. For organizational purposes, I will close this issue. Please, feel to free to open a new issue whenever you need.

**Closed as completed by devajmeireles** 2023-08-18 19:47 UTC
Labels: unreproducible
