### ISSUE TITLE
Using factories in beforeAll/afterAll hook throws InvalidArgumentException

### ISSUE THREAD

**Issue by rihardssceredins** [pestphp/pest#246] opened 2020-12-29 14:02 UTC
Hey,

Reproducible with clean project:
```
laravel new pest-beforeAll
composer require pestphp/pest --dev --with-all-dependencies
composer require pestphp/pest-plugin-laravel --dev
php artisan pest:install
```

Refactor the default `ExampleTest.php` to Pest and try to create `User` factory in `beforeAll`/`afterAll` hook:

```
<?php

use App\Models\User;
use function Pest\Laravel\be;
use function Pest\Laravel\get;

beforeAll(function(){
  be(User::factory()->create());
});

test('basic test', function(){
  get('/')->assertStatus(200);
});
```

Run `php artisan test` and it will fail with:

<img width="740" alt="Screenshot 2020-12-29 at 15 49 37" src="https://user-images.githubusercontent.com/23099574/103288560-ccfad700-49ed-11eb-8d66-74ca9dca9626.png">

When using `beforeEach` instead of `beforeAll` the tests pass. ✨

Sorry that this didn't come with a pull request - haven't tinkered with reflection that deep and I bet given that it's reproducible someone from the core contributors will have easier time fixing this. Alternatively if someone could provide some pointers as to what might be the cause I can take a look and try to figure it out. 🤓

**Comment by owenvoke** [comment] 2020-12-29 14:16
This is a known "issue", `beforeAll` / `afterAll` are called before (or after) the class has been instantiated (they are the equivalents of `@beforeClass` and `@afterClass` in PHPUnit). So the framework hasn't been booted at that point. 👍🏻 See https://github.com/pestphp/pest/issues/237 and https://github.com/pestphp/pest/issues/33#issuecomment-658022624. 🙂 I think that Nuno was thinking about a possible way of resolving this though. 🤔

**Comment by nunomaduro** [comment] 2020-12-29 19:55
What is the issue here?

**Comment by owenvoke** [comment] 2020-12-29 20:12
It's not really an issue, just a lot of people seem to get confused with `beforeAll()` / `beforeEach()` not working like how `setUp()` and `tearDown()` work.

**Comment by nunomaduro** [comment] 2020-12-30 01:53
Yeah - @rihardssceredins please take a look at this docs: https://pestphp.com/docs/setup-and-teardown.

**Closed by nunomaduro** 2020-12-30 01:53 UTC

**Comment by rihardssceredins** [comment] 2021-01-08 09:46
@nunomaduro it doesn't mention there the fact that the framework hasn't
booted and you can only run basic code. Would be a nice touch for new
adopters who don't know/haven't used PHPUnit and jump right in to PestPHP.
🚀

**Comment by rihardssceredins** [comment] 2021-01-08 09:48
I must admit that even I didn't know about the `@beforeClass` restrictions
because I hadn't used them in Laravel.

**Comment by owenvoke** [comment] 2021-01-08 09:52
I'll add a note about this to the docs soon. 👍🏻

**Comment by nunomaduro** [comment] 2021-01-08 10:47
That note seems Laravel specific.

**Comment by owenvoke** [comment] 2021-01-08 11:04
Yeah, I'm trying to think of a more generic sentence. This mostly seems to have come up in Laravel projects, and the official documentation for PHPUnit isn't particularly helpful about this. 🤔 https://phpunit.readthedocs.io/en/latest/annotations.html#beforeclass

I guess for the PHPUnit one, it runs after the class has been instantiated (as it has to), so this isn't an issue.

**Comment by Anthodev** [comment] 2021-02-04 08:42
I second the request. I'm starting using Pest too since yesterday and it take me a while to understand that the class isn't instantiated during beforeAll() which i find it odd, so i thought i was doing something wrong.

So i think that beforeAl() should be instantiated after the class is initialized, it should be a good gain on performance time if we have to load the fixtures once for the class instead of each test.

**Comment by iamkhusainov7** [comment] 2022-11-13 21:55
@ilyavaiser I agree with you, as I am having the same issue. I need to test a table sorting, and for each test case, I need to seed my DB again and again with the same data, which influences the performance of the test. In fact, it should be done only once.

**Comment by MichaelRushton** [comment] 2023-02-16 11:14
It's far from ideal, but until something is implemented properly you could just run whatever you need to run before all tests in the global space.

```
$connection = new Connection;

it('can execute', function () use ($connection)
{

  expect($connection->execute("SELECT * FROM users"))
  ->toBeInstanceOf(Response::class);

});
```

**Comment by ilejohn-official** [comment] 2023-05-24 15:53
@nunomaduro it's obvious from the previous comments and likes that a lot of devs want to be able to access framework functionalities, e.g factories, artisan commands, etc once before the whole test runs and hence access to the application's booted state. Is there a way out to do this without having to repeat executions in the `beforeEach` hook?

**Comment by Thinkro** [comment] 2023-06-01 10:56
Just encountered this, and here Pest seems to be lacking

**Comment by khiangte85** [comment] 2023-07-13 07:02
Any work around for this Guys?  my use case is i want to run some seeder before test run not after each tests

**Comment by rihardsgrislis** [comment] 2023-07-25 11:28
I guess this is resolved now via: https://pestphp.com/docs/pest-spicy-summer-release#content-describe-blocks. 👏🏼

**Comment by potsky** [comment] 2023-11-02 11:22
No solution for me...
We have created functions BlablahSetup() and I call this on the first line of each test...

**Comment by davidbirkin** [comment] 2024-01-15 13:29
So can someone enlighten me... is there any way whatsoever to run ~migrations~ seeders before running all tests in a file? A simple yes, no will suffice. If the answer is no I will resort to @potsky 's solution

**Comment by tipul07** [comment] 2025-01-14 17:46
A workaround would be to have in `Pest.php` (or in test files directly) a class (let's say `BootstrapBeforeEachTest`):

```php
class BootstrapBeforeEachTest {
    private static bool $didRun = false;

    public static function didRun(?bool $run = null): bool {
        if($run === null) {
            return self::$didRun;
        }

        self::$didRun = $run;
        return self::$didRun;
    }
}
```

and `beforeEach()` would look like:
```php
beforeEach(function () {
    if(!BootstrapBeforeEachTest::didRun()) {
        // Some things which are run only before first test
        Artisan::call('migrate:fresh');
        Artisan::call('config:clear');

        BootstrapBeforeEachTest::didRun(true);
    }
});
```

It worked for me, so I hope it helps.

**Comment by aldobarr** [comment] 2025-07-10 11:01
The problem is clearly an issue with poor naming here. If I'm declaring `before all` inside of a test file, the intention is clear. I want to run this closure before *all* of THESE tests. That's why I'm declaring the closure inside of this test file specifically and not somewhere more global. Therefore, a hook named `beforeAll` should not be running before the test runner is instantiated. I fully expect `$this` to be accessible inside `beforeAll` just as it is inside `beforeEach`

If I need to run code before the runner is instantiated, that should be a global before all, i.e.

```
// maybe a different name but the intention here is clear. I need this particular closure to run before my entire test suite
pest()->beforeAll(fn() => echo 'my test suite is starting')
	->in('Feature', 'Unit');
```

Then if it's desirable for individual tests to have access to this global before runner hook, then it should be renamed to something more clear. `beforeSetup` or `beforeRunner` or something.

For me, I genuinely can't understand the logic behind these hooks at all. What is the point of these hooks? I genuinely can't do anything to setup my tests without having to do something hacky and completely unnecessary using `beforeEach` and that's a massive deal breaker for me. If we look at something like mocha which uses the same naming schema, `beforeAll` runs in the context of setting up a particular mocha test, not the entire suite. And that makes perfect sense.

Yet for whatever reason the contributors here seem content with saying this obvious glaring issue is perfectly okay because we created this bug on purpose. 👍 

Edit: and you also can't setup shared variables without using the clunky data nonsense 😂
