### ISSUE TITLE
--watch doesn't show colors

### ISSUE THREAD

**Issue by grafst** [pestphp/pest#789] opened 2023-04-21 15:44 UTC
When running pest 2.5.2 with the --watch flag, it doesn't show colors.
Is that on purpose?
<img width="611" alt="2023-04-21_17-43-05" src="https://user-images.githubusercontent.com/8471055/233678744-a956d562-33d8-404c-a29f-b2485ed6cf73.png">

Terminal: iterm2 v3.4.19

**Comment by jeroenboumans** [comment] 2023-05-23 10:32
For me adding the `--colors=always` works.

**Comment by nunomaduro** [comment] 2023-05-23 10:55
@jeroenboumans Can you make a pull request to fix this?

**Comment by jeroenboumans** [comment] 2023-05-23 17:41
@grafst are you _pesting_ using the laravel-plugin?
@nunomaduro cannot reproduce this issue using only the pestphp/pest repo.

**Comment by Thinkro** [comment] 2023-06-01 12:19
<img width="560" alt="Screenshot_2023-05-25_at_17 17 18" src="https://github.com/pestphp/pest/assets/113018109/dfab6ebe-f2ba-4132-af7f-3ec51d7e59b4">

No colors and exits after run, using Laravel latest on Sail.

**Comment by grafst** [comment] 2023-06-09 18:44
> @grafst are you _pesting_ using the laravel-plugin?
> @nunomaduro cannot reproduce this issue using only the pestphp/pest repo.

yes using the Laravel plugin

**Comment by Thinkro** [comment] 2023-06-13 10:04
Using `sail pest --watch --colors=always` adds color, but `--watch` just exists after first run (unrelated to if --colors=always is used or not)

**Comment by azmy60** [comment] 2023-08-07 07:40
@Thinkro I had a similar issue. In my case, I had to install `fswatch` since the plugin uses that command.

**Comment by devajmeireles** [comment] 2023-08-18 15:23
@grafst ,

Thanks for your report. According to my latest tests, I have not been able to reproduce the same behavior, so I will close this issue to preserve the organization believing that this is not an issue. Feel free to open a new issue, whatever you need.

**Closed as completed by devajmeireles** 2023-08-18 15:23 UTC
Labels: bug
