### ISSUE TITLE
Can't install on Laravel 10

### ISSUE THREAD

**Issue by benjivm** [pestphp/pest#664] opened 2023-02-14 18:01 UTC
Hello, I am following the [Laravel 10 upgrade guide](https://laravel.com/docs/10.x/upgrade#updating-dependencies), which says to update  `nunomaduro/collision` to `^7.0`, but this seems to conflict with PEST:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pestphp/pest[v0.1.0, ..., v0.2.4] require php ^7.3 -> your php version (8.1.11) does not satisfy that requirement.
    - pestphp/pest[v0.3.0, ..., v0.3.19, v1.0.0, ..., v1.4.0] require nunomaduro/collision ^5.0 -> found nunomaduro/collision[v5.0.0, ..., v5.11.0] but it conflicts with your root composer.json require (^7.0).
    - pestphp/pest[v1.5.0, ..., v1.17.0] require nunomaduro/collision ^5.4.0 -> found nunomaduro/collision[v5.4.0, ..., v5.11.0] but it conflicts with your root composer.json require (^7.0).
    - pestphp/pest[v1.18.0, ..., v1.21.1] require nunomaduro/collision ^5.4.0|^6.0 -> found nunomaduro/collision[v5.4.0, ..., v5.11.0, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - pestphp/pest[v1.21.2, ..., v1.22.1] require nunomaduro/collision ^5.10.0|^6.0 -> found nunomaduro/collision[v5.10.0, v5.11.0, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - pestphp/pest[v1.22.2, ..., v1.22.4] require nunomaduro/collision ^5.11.0|^6.3.0 -> found nunomaduro/collision[v5.11.0, v6.3.0, v6.3.1, v6.3.2, v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires pestphp/pest * -> satisfiable by pestphp/pest[v0.1.0, ..., v0.3.19, v1.0.0, ..., v1.22.4].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require pestphp/pest:*" to figure out if any version is installable, or "composer require pestphp/pest:^2.1" if you know which you need.
```

**Comment by Tray2** [comment] 2023-02-14 18:11
Confirmed, I have the same issue.

**Comment by divdax** [comment] 2023-02-14 19:31
Same here

**Comment by luanfreitasdev** [comment] 2023-02-14 20:33
Probably Laravel 10 already brought phpunit 10.x by default, but it supports 9.x

As pest v1 has limited support for phpunit 9.x you can install it like this and wait for pest 2.x:

```json
"nunomaduro/collision": "^6.0",
"phpunit/phpunit": "^9.6",
```
Run
```bash
composer update
```

**Comment by Tray2** [comment] 2023-02-14 20:33
Did a new test upgrading my project to Laravel 10.
As long as I don't change the phpunit version from ^9.5.10 => ^10.0, it works.
So it looks like PestPhp needs to be updated to support nunomaduro/collision ^7.0

**Comment by dansysanalyst** [comment] 2023-02-14 21:10
Hello everybody,

👍 I have installed Pest in Laravel 10:

Used the Laravel installer to create a new project and enter the folder:

```shell
laravel new my-app && cd my-app
```

Downgraded PHP Unit and Collision
```shell
composer require phpunit/phpunit:^9.6 nunomaduro/collision:^6.1 pestphp/pest --dev --with-all-dependencies
```

Init Pest

```shell
php artisan pest:install
```

and run tests:

```shell
php artisan test
```

---

Alternatively, I made sure to have the latest Laravel installed:


```shell
composer global upgrade laravel/installer
```

Then, created a new project with Pest tests and enter the folder:

```shell
laravel new my-app --pest && cd my-app
```

and finally, ran the tests:

```shell
php artisan test
```


*note*: PHPUnit v10.0 and Collision v7.0 will be supported in Pest v2 (yet to be released).

**Comment by pcmehrdad** [comment] 2023-02-14 23:35
Same here

**Comment by lpheller** [comment] 2023-02-15 08:16
Running `laravel new my-app --pest` (newest installer) will work, as it fixes `nunomaduro/collision` back to `v6.4`. 
Which sadly results in not being able to use the new `--profile` flag when using `php artisan test`.

**Comment by nunomaduro** [comment] 2023-02-15 09:16
Pest 2 will be released end February, and it will bring Collision to 7 support, and --profile support. Meanwhile, please follow these instructions: https://pestphp.com/docs/installation#installation

**Closed as completed** 2023-02-15 10:50 UTC

**Comment by Sergiobop** [comment] 2023-03-06 08:54
Hi @nunomaduro , is there an estimated date of the 2.0 release?
Thanks a lot for your work

**Comment by Andre-ADPC** [comment] 2023-06-08 11:58
Hi @nunomaduro, 
In reference to the new PEST 2.x release and watching the [Anouncement](https://www.youtube.com/watch?v=9EGPo_enEc8), I thought it obvious to start using PEST 2.

However, I'm baffled about how to create the "Pest.php" config file using the Pest documentation, vs others blaming **`"collision"`** for causing the issue. And after various attempts, I ended up here, on a closed issue, but it seemed the best place to place my issue request though.

**My Project setup after initial installations (not all packages are shown):**
- Laravel framework:    10.10
- PHP:                             8.1
- Collision:                      7.0
- PEST:                            2.6
- Fortify:                         1.17

All packages installed seamlessly without errors. No starter kits were applied as I want to build a Vue-Nuxt bridge, using Laravel + Fortify as an API. (If my full `composer` or `composer.lock` files will help, I can provide them.)

#### Using PEST 2 Installation Guide:
Applying the **Pest 2** installation guidelines: [your link from Feb 15 2023, above](https://pestphp.com/docs/installation#installation) gives the same method as the latest [PEST 2 installation guide](https://pestphp.com/docs/installation)

`λ   composer require pestphp/pest --dev --with-all-dependencies`

But, running `./vendor/bin/pest --init` Fails:

`λ   ./vendor/bin/pest --init
'.' is not recognized as an internal or external command,
operable program or batch file.`

Trying my luck:
`λ   /vendor/bin/pest --init
The system cannot find the path specified.`

#### Using Laravel Plugin:
OK, so let's go and try using the Laravel Plugin `"pestphp/pest-plugin-laravel": "^2.0"`:
 The approach in the [PEST 2 Laravel Plugin documentation](https://pestphp.com/docs/plugins#content-laravel) never mentions how the `Pest.php` config file should be initialized or created.

 I can create PEST Test entry-points, but the `Pestphp` config file is still missing, so my gut tells me this won't work or end well at all.

This works but obviously not indicating the configuration is complete:
Create an Example Unit Test — PEST-MyTest:  `λ   php artisan pest:test PEST-HomePageTest --unit`

`λ   composer require pestphp/pest-plugin-laravel --dev` and then follow up with `λ   php artisan pest:install` also fails:

`λ   php artisan pest:install`

>    ERROR  Command "pest:install" is not defined. Did you mean one of these?
> 
>   ⇂ migrate:install
>   ⇂ pest:dataset
>   ⇂ pest:test
>   ⇂ sail:install
>   ⇂ test

Do you have any pointers on where one needs to go to get a work-around or how the `Pest.php` config file problem should be resolved, please?

All the best.

**Comment by junnysolanovega** [comment] 2023-06-11 21:33
I have the same problem as @Andre-ADPC. I am working in a Laravel Sail environment. Thanks for the help.

**Comment by owenvoke** [comment] 2023-06-11 22:13
@Andre-ADPC, looking at your shell prompt (`λ`) are you by any chance using Cmder (and Windows)? 👀 If so, try using `vendor/bin/pest --init` (removing the `./` as Windows does not support it.

Regarding the `artisan pest:install` command, I'm pretty sure this was removed in 2.x, in favour of the general `vendor/bin/pest --init` command.

**Comment by junnysolanovega** [comment] 2023-06-12 00:39
Hello, I am detailing my experience to execute the PEST command from my environment in Laravel Sail, to do so it is necessary to use the sail command.

For example, to initialize PEST and create the configuration file you would run:  _**./vendor/bin/sail pest --init**_

Now if you want to run the tests you can use the command: _**./vendor/bin/sail pest**_

For more practicality you can create an alias in your operating system, this is an example in Linux or Windows (WSL): _**alias pest='./vendor/bin/sail pest'**_

I hope it will be useful to others with the same case.

Greetings,

**Comment by Andre-ADPC** [comment] 2023-06-12 17:29
> @Andre-ADPC, looking at your shell prompt (`λ`) are you by any chance using Cmder (and Windows)? 👀 If so, try using `vendor/bin/pest --init` (removing the `./` as Windows does not support it.
> 
> Regarding the `artisan pest:install` command, I'm pretty sure this was removed in 2.x, in favour of the general `vendor/bin/pest --init` command.

@owenvoke , thanks for your input, and yes you are correct.  I have it set up in Windows Terminal and have tried it as per your suggestion but that doesn't work either. I will rather use bash instead. 

The PEST team can do well by mentioning it in the docs, though.

As for the second part about using the artisan command, yes true, but due to the confusing advice I've seen in various articles and even on Stackoverflow, I tried that to try my luck. I'll "bash" it a bit and see what happens.

**Comment by Andre-ADPC** [comment] 2023-06-12 17:54
Yes using bash via MINGW64 on Windows Terminal does the trick. `~/tests/Pest.php ` was created successfully.
