### ISSUE TITLE
[Bug]: Incomprehensible error message if a dataSet does not exist

### ISSUE THREAD

**Issue by julien-boudry** [pestphp/pest#963] opened 2023-09-19 21:27 UTC
### What Happened

```shell
$ vendor/bin/pest
Typed static property P\Tests\Feature::$__latestDescription must not be accessed before initialization
```

### How to Reproduce

Supposing that there is not any 'foo' dataset.

```php
<?php
// tests/Feature.php

use NunoMaduro\SkeletonPhp\Example;

it('foo', function (string $foo) {
    expect($foo)->toBe('42');
})->with('foo');
```

### Pest Version

2.19

### PHP Version

8.2

### Operation System

Linux

**Comment by devajmeireles** [comment] 2023-09-20 13:52
Hey, @julien-boudry ! Thanks for your report.

According to my tests, I was unable to reproduce the same issue:

![CleanShot 2023-09-20 at 10 50 23](https://github.com/pestphp/pest/assets/60591772/0a81b510-3c6c-4ffb-a0c0-9cf4b23ee220)

Could you try again in the latest version of Pest? I noticed you said the version is `2.19`, but Pest is at `2.19.2` now.

**Comment by julien-boudry** [comment] 2023-09-20 14:10
Hi @devajmeireles 

I use Pest 2.19.2, still the bug.

Easy to test with this example: https://github.com/julien-boudry/Tests-Pest-from-skeleton/blob/main/tests/Feature.php (can be run in a minute with Github codespace in browser).

I also realized while preparing this example that if a valid test exists before it, then the bug doesn't recur. This is in line with the PR proposed by @elminson

**Comment by devajmeireles** [comment] 2023-09-20 16:28
> Hi @devajmeireles
> 
> I use Pest 2.19.2, still the bug.
> 
> Easy to test with this example: https://github.com/julien-boudry/Tests-Pest-from-skeleton/blob/main/tests/Feature.php (can be run in a minute with Github codespace in browser).
> 
> I also realized while preparing this example that if a valid test exists before it, then the bug doesn't recur. This is in line with the PR proposed by @elminson

I was able to reproduce the same, but I don't think it's something we need to worry about. By following the documentation, anyone will know how to create datasets, so this is the kind of case that wouldn't make a big difference.

In any case, thank you for your report. I will mark this ticket as a suggestion. According to our organization, I'll close this issue. Feel free to open a new issue whenever necessary.

**Closed as completed by devajmeireles** 2023-09-20 16:28 UTC
Labels: suggestion

**Comment by julien-boudry** [comment] 2023-09-22 08:29
Hi,

I don't think it should be taken so lightly. It's a bug that's very easy to reproduce and produces a PHP error. Admittedly, it's unlikely to occur in a project that's already well-established. But a user wishing to initiate a project or just test Pest, and committing, for example, a typo error, or writing his test before his dataSet : he is directly confronted with a Pest crash, which doesn't inspire the best confidence in a testing framework (therefore in principle particularly robust).

**Comment by michael-rubel** [comment] 2023-10-10 07:55
@julien-boudry It has occurred in a project that's already well-established. We have a lot of tests & datasets, and almost in every upgrade, there are some glitches or even critical errors on the Pest side. Honestly, I'm considering going back to PHPUnit.
