### ISSUE TITLE
The feature "Filter by dirty files" requires "git"

### ISSUE THREAD

**Issue by jasonmccallister** [pestphp/pest#837] opened 2023-06-15 13:32 UTC
I get this one randomly through out the day. I'm running my site with ddev and connected via `ddev ssh`. I can run the command multiple times successfully, but at least ~10 times a day - in the same terminal session - I get the following error:

```
The feature "Filter by dirty files" requires "git".
```

This happens when running `php artisan test --dirty` and `./vendor/bin/pest --dirty`.

**Details**

PHP: 8.2.3
Pest: 2.6.3

**Comment by owenvoke** [comment] 2023-06-15 13:52
Hmm, I'm assuming this is due to [this check](https://github.com/pestphp/pest/blob/c0af671ca214c1fb43133daaa0a667f57b11ef10/src/TestCaseFilters/GitDirtyTestCaseFilter.php#L49).

It only checks whether the command failed, not whether Git actually exists. So it's probably just that the command returned an invalid exit code, and might be hiding the underlying issue.

**Comment by jasonmccallister** [comment] 2023-06-15 20:09
Alright, I edited that file in vendor and added the following:

```
if (! $process->isSuccessful()) {
    dd($process->getErrorOutput());
    throw new MissingDependency('Filter by dirty files', 'git');
}
```

I finally hit that error and this is the output:

```
fatal: detected dubious ownership in repository at '/var/www/html'\n
To add an exception for this directory, call:\n
\n
\tgit config --global --add safe.directory /var/www/html\n
```

**Comment by jasonmccallister** [comment] 2023-06-24 18:37
Running `git config --global --add safe.directory /var/www/html` does resolve the problem, but it still occurs randomly. I'm assuming this has something to do with `ddev` and mutagen mounts?

**Comment by devajmeireles** [comment] 2023-08-18 19:41
Hey, @jasonmccallister . Thanks for your report.

I was not able to reproduce this, so I assume this issue is specific to your environment. To improve our organization, I will close this topic. Please feel free to open a new topic, whatever you need.

**Closed as completed by devajmeireles** 2023-08-18 19:41 UTC
Labels: unreproducible

**Comment by kerunaru** [comment] 2024-06-27 10:50
@jasonmccallister Just four your information. This happens when Docker mounts the volume with your code; your user used to log in the container differs from the one who creates all the directory hierarchy and git complains about that.
